name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: make
    - name:  Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: pagerank.bin
        path: build/page_rank
    - name: Benchmark
      run: ./benchmark.sh
    - name: Create commit comment
      uses: peter-evans/commit-comment@v3
      with: 
        body-path: benchmark.md
      
  test:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: make test
      
    - name: Run
      run: make run_test
